-- MySQL Script generated by MySQL Workbench
-- mar. 27 août 2019 16:46:27 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Afronvention
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Afronvention
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Afronvention` DEFAULT CHARACTER SET utf8 ;
USE `Afronvention` ;

-- -----------------------------------------------------
-- Table `Afronvention`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Afronvention`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(245) NOT NULL,
  `password` VARCHAR(245) NOT NULL,
  `name` VARCHAR(245) NOT NULL,
  `status` VARCHAR(245) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Afronvention`.`Inventors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Afronvention`.`Inventors` (
  `idInventors` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NOT NULL,
  `birthday_date` DATE NULL,
  `death_date` DATE NULL,
  `country` VARCHAR(245) NOT NULL,
  `job` VARCHAR(245) NOT NULL,
  `history` VARCHAR(845) NULL,
  PRIMARY KEY (`idInventors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Afronvention`.`Inventions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Afronvention`.`Inventions` (
  `idInventions` INT NOT NULL AUTO_INCREMENT,
  `name_invention` VARCHAR(245) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idInventions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Afronvention`.`Inventions_has_Inventors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Afronvention`.`Inventions_has_Inventors` (
  `Inventions_idInventions` INT NOT NULL,
  `Inventors_idInventors` INT NOT NULL,
  PRIMARY KEY (`Inventions_idInventions`, `Inventors_idInventors`),
  INDEX `fk_Inventions_has_Inventors_Inventors1_idx` (`Inventors_idInventors` ASC) VISIBLE,
  INDEX `fk_Inventions_has_Inventors_Inventions_idx` (`Inventions_idInventions` ASC) VISIBLE,
  CONSTRAINT `fk_Inventions_has_Inventors_Inventions`
    FOREIGN KEY (`Inventions_idInventions`)
    REFERENCES `Afronvention`.`Inventions` (`idInventions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventions_has_Inventors_Inventors1`
    FOREIGN KEY (`Inventors_idInventors`)
    REFERENCES `Afronvention`.`Inventors` (`idInventors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
